=== sherbold/replication-kit-emse-2016-local-models/replication-kit/experimentconfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="experimentconfig"
    elementFormDefault="qualified"
    xmlns="experimentconfig"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="1">
        <xs:element name="partialconfig" type="pathType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="loader" type="datapathType" minOccurs="0" maxOccurs="1"/>
        <xs:element name="resultspath" type="pathType" minOccurs="0" maxOccurs="1"/>
        <xs:element name="versionfilter" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="testVersionfilter" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="trainVersionfilter" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisepreprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwiseselector" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisepostprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="setwisetrainer" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="preprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="pointwiseselector" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="postprocessor" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="trainer" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="eval" type="setupType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="partialconfig" type="pathType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="datapathType">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="datalocation" type="xs:string" />
    <xs:attribute name="relative" type="xs:boolean" default="true"/>
  </xs:complexType>
  <xs:complexType name="pathType">
    <xs:attribute name="path" type="xs:string" />
    <xs:attribute name="relative" type="xs:boolean" default="true"/>
  </xs:complexType>
  <xs:complexType name="setupType">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="param" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== sherbold/replication-kit-emse-2016-local-models/exp-MDP/config/NONORM-US.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="experimentconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="experimentconfig experimentconfig.xsd">
<loader name="NasaARFFFolderLoader" datalocation="exp-MDP/data" relative="false"/>
<versionfilter name="MinClassNumberFilter" param="5" />
<postprocessor name="Undersampling" param="" />
<trainer name="WekaLocalEMTraining" param="SMORBFLocalEM weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
<trainer name="WekaLocalFQTraining" param="SMORBFLocalFQ weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
<resultspath path="exp-MDP/results"/>
<eval name="NormalWekaEvaluation" param="" />
</config>

=== sherbold/replication-kit-emse-2016-local-models/replication-kit/exp-JAVAPROCESS/config/US.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="experimentconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="experimentconfig experimentconfig.xsd">
<loader name="ARFFFolderLoader" datalocation="exp-JAVAPROCESS/data" relative="false"/>
<versionfilter name="MinClassNumberFilter" param="5" />
<setwisepreprocessor name="Normalization" param=""/>
<postprocessor name="Undersampling" param="" />
<trainer name="WekaTraining" param="SMORBF weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
<trainer name="WekaLocalEMTraining" param="SMORBFLocalEM weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
<trainer name="WekaLocalFQTraining" param="SMORBFLocalFQ weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
<resultspath path="exp-JAVAPROCESS/results"/>
<eval name="NormalWekaEvaluation" param="" />
</config>

=== sherbold/replication-kit-emse-2016-local-models/exp-JAVASTATIC/config/US-ENTITYKNN.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="experimentconfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="experimentconfig experimentconfig.xsd">
<loader name="CSVFolderLoader" datalocation="exp-JAVASTATIC/data" relative="false"/>
<versionfilter name="MinClassNumberFilter" param="5" />
<setwisepreprocessor name="Normalization" param=""/>
<pointwiseselector name="TurhanFilter" param="10" />
<postprocessor name="Undersampling" param="" />
<trainer name="WekaTraining" param="SMORBF weka.classifiers.functions.SMO -K weka.classifiers.functions.supportVector.RBFKernel" />
<resultspath path="exp-JAVASTATIC/results"/>
<eval name="NormalWekaEvaluation" param="" />
</config>
